export enum HackathonStatus {
  HACKATHON_CREATED = "HACKATHON_CREATED",
  REGISTRATION_STARTED = "REGISTRATION_STARTED",
  REGISTRATION_ENDED = "REGISTRATION_ENDED",
  IN_PROGRESS = "IN_PROGRESS",
  HACKATHON_ENDED = "HACKATHON_ENDED",
  HACKATHON_EXPIRED = "HACKATHON_EXPIRED",
}
